#!/usr/bin/env python3
"""
Patch Android project generated by Tauri to enable camera permissions:
1. Adds CAMERA permission and features to AndroidManifest.xml so Android OS grants camera access.
"""

import os
import glob

def patch_manifest():
    manifest_path = os.path.join('src-tauri', 'gen', 'android', 'app', 'src', 'main', 'AndroidManifest.xml')
    if not os.path.exists(manifest_path):
        print(f"[Patch] Manifest not found at {manifest_path}, skipping.")
        return False

    with open(manifest_path, 'r', encoding='utf-8') as f:
        content = f.read()

    camera_perms = (
        '    <uses-permission android:name="android.permission.CAMERA" />\n'
        '    <uses-feature android:name="android.hardware.camera" android:required="false" />\n'
        '    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />\n'
    )

    if 'android.permission.CAMERA' not in content:
        content = content.replace('<application', camera_perms + '    <application')
        with open(manifest_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"[Patch] Successfully injected CAMERA permissions into {manifest_path}")
    else:
        print(f"[Patch] CAMERA permission already present in {manifest_path}")
    return True


if __name__ == '__main__':
    print("[Patch] Applying Android camera permissions to AndroidManifest.xml...")
    p1 = patch_manifest()
    print(f"[Patch] Done: manifest={p1}")
