#!/usr/bin/env python3
"""
Patch Android project generated by Tauri to enable camera permissions:
1. Adds CAMERA permission and features to AndroidManifest.xml
2. Adds WebView onPermissionRequest handler in MainActivity.kt to bridge Web APIs to Android's runtime permission prompt.
"""

import os
import glob
import re

def patch_manifest():
    manifest_path = os.path.join('src-tauri', 'gen', 'android', 'app', 'src', 'main', 'AndroidManifest.xml')
    if not os.path.exists(manifest_path):
        print(f"[Patch] Manifest not found at {manifest_path}, skipping.")
        return False

    with open(manifest_path, 'r', encoding='utf-8') as f:
        content = f.read()

    camera_perms = (
        '    <uses-permission android:name="android.permission.CAMERA" />\n'
        '    <uses-feature android:name="android.hardware.camera" android:required="false" />\n'
        '    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />\n'
    )

    if 'android.permission.CAMERA' not in content:
        content = content.replace('<application', camera_perms + '    <application')
        with open(manifest_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"[Patch] Successfully injected CAMERA permissions into {manifest_path}")
    else:
        print(f"[Patch] CAMERA permission already present in {manifest_path}")
    return True


def patch_main_activity():
    pattern = os.path.join('src-tauri', 'gen', 'android', 'app', 'src', 'main', 'java', '**', 'MainActivity.kt')
    matches = glob.glob(pattern, recursive=True)
    if not matches:
        print("[Patch] MainActivity.kt not found in generated Android tree, skipping.")
        return False

    path = matches[0]
    kotlin_code = """package com.notes.workstation

import android.Manifest
import android.content.pm.PackageManager
import android.os.Bundle
import android.webkit.PermissionRequest
import android.webkit.WebChromeClient
import android.webkit.WebView
import androidx.activity.result.contract.ActivityResultContracts
import androidx.core.content.ContextCompat
import app.tauri.TauriActivity

class MainActivity : TauriActivity() {
    private var pendingRequest: PermissionRequest? = null

    private val requestPermissionLauncher = registerForActivityResult(
        ActivityResultContracts.RequestPermission()
    ) { isGranted: Boolean ->
        if (isGranted) {
            pendingRequest?.grant(pendingRequest?.resources)
        } else {
            pendingRequest?.deny()
        }
        pendingRequest = null
    }

    override fun onWebViewCreate(webView: WebView) {
        super.onWebViewCreate(webView)
        webView.webChromeClient = object : WebChromeClient() {
            override fun onPermissionRequest(request: PermissionRequest) {
                if (request.resources.contains(PermissionRequest.RESOURCE_VIDEO_CAPTURE)) {
                    if (ContextCompat.checkSelfPermission(this@MainActivity, Manifest.permission.CAMERA)
                        == PackageManager.PERMISSION_GRANTED) {
                        request.grant(request.resources)
                    } else {
                        pendingRequest = request
                        requestPermissionLauncher.launch(Manifest.permission.CAMERA)
                    }
                } else {
                    request.grant(request.resources)
                }
            }
        }
    }
}
"""
    with open(path, 'w', encoding='utf-8') as f:
        f.write(kotlin_code)
    print(f"[Patch] Successfully patched {path} with camera onPermissionRequest bridge")
    return True


if __name__ == '__main__':
    print("[Patch] Applying Android camera permissions and WebChromeClient bridge...")
    p1 = patch_manifest()
    p2 = patch_main_activity()
    print(f"[Patch] Done: manifest={p1}, main_activity={p2}")
